web/router.ex
defmodule Tattler.Router do
  use Tattler.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Tattler.Authentication, repo: Tattler.Repo
  end

  pipeline :browser_authenticated do
    plug :require_authenticated_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Tattler do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [ :new, :create ]
    resources "/sessions", SessionController, only: [ :new, :create, :delete ]
  end

  scope "/", Tattler do
    pipe_through [ :browser, :browser_authenticated ]

    resources "/monitors", MonitorController, only: [ :index, :new, :create, :edit, :update, :delete ]
  end


  # Other scopes may use custom stacks.
  # scope "/api", Tattler do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Tattler.LayoutView do
  use Tattler.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Tattler!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <ol class="breadcrumb text-right">
          <%= if Tattler.Authentication.logged_in?(@conn) do %>
            <li><%= link "Logout",
                  to: session_path(@conn, :delete, Tattler.Authentication.current_user(@conn)),
                  method: :delete
                %>
            </li>
          <% else %>
            <li><%= link "Register", to: user_path(@conn, :new) %></li>
            <li><%= link "Login", to: session_path(@conn, :new) %></li>
          <% end %>
        </ol>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>